## 1번. random메소드를 사용하되 어려번 실행되어도 같은 값이 나오는 (10,) 형태의 numpy array를 만어 주세요

소문제
1. array 요소의 합, 최댓값, 최댓값일때의 index 번호룰 출력하세요 
- 브로드케스팅 기능을 이용해서 각 값의 크기를 2배 해주세요
- 브로드케스팅을 이용하여 +3 값을 해주세요
- 행렬을 같은 크기의 행렬을 만들어서 두 행렬의 곱을 구하세요(기존의 array와 다르게 값이 계속 바뀌게 만들어주세요)
- 위에서 만든 행열과 기본의 행렬의 np.dot 연산을 진행해 주세요


In [2]:
import numpy as np

In [9]:
# 1번
np.random.seed(0)
data = np.random.rand(10)
data

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [11]:
# 2번
data = data*2
data

array([1.09762701, 1.43037873, 1.20552675, 1.08976637, 0.8473096 ,
       1.29178823, 0.87517442, 1.783546  , 1.92732552, 0.76688304])

In [12]:
# 3번
data = data + 3
data

array([4.09762701, 4.43037873, 4.20552675, 4.08976637, 3.8473096 ,
       4.29178823, 3.87517442, 4.783546  , 4.92732552, 3.76688304])

In [26]:
# 4번
data2 = np.random.rand(10)
data2
data3 = data2 * data
data3

array([3.67371354, 1.62843829, 1.8330416 , 3.64775814, 3.10167787,
       3.02094074, 0.38839667, 4.39838738, 3.51929938, 3.76253985])

In [28]:
# 5번
data4 = np.dot(data, data3.T)
data4

123.85261759768939

## 2번

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 형태를

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]) 
       
       와
       
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
       
형태로 변경하세요
      

In [32]:
data = np.arange(10)
data
#1
data = data.reshape(2,-1)
data

#2
data = data.reshape(5,-1)
data

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## 3번. 마크다운에 있는 array를 복사하여 다음 문제를 풀어주세요

data = np.array([ [[1,2,3,4], 
                  [5,6,7,8], 
                  [9,10,11,12]], 
                  [[21,22,23,24], 
                   [25,26,27,28], 
                   [29,30,31,32]] ])
에서 

1. 이 베열의 차원, 모양을 출력하세요 
- 26을 뽑아주세요
- 7 을 39로 변경해주세요


In [36]:
data = np.array([ [[1,2,3,4], [5,6,7,8], [9,10,11,12]], [[21,22,23,24], [25,26,27,28], [29,30,31,32]] ]) 
#3-1번
print(data.ndim)
print(data.shape)

3
(2, 3, 4)


In [39]:
#3-2번
data[1][1][1]

26

In [42]:
#3-3번
data[0][1][2] = 39
data

array([[[ 1,  2,  3,  4],
        [ 5,  6, 39,  8],
        [ 9, 10, 11, 12]],

       [[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]])

## 4번. 마크다운에 있는 array를 복사하여 다음 문제를 풀어주세요


x = np.array([[1,2,3],[5,6,7]])
y = np.array([[33,44,55], [11,22,66]])
x,y

이 두 array를 이용해서 concatenate 와 array 결합(np.array([x,y]))을 출력하고
두 가지 결합 방법의 차이점을 기술하세요

In [43]:
x = np.array([[1,2,3],[5,6,7]]) 
y = np.array([[33,44,55], [11,22,66]])
# concatenate
data = np.concatenate([x,y])
data

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [33, 44, 55],
       [11, 22, 66]])

In [45]:
# array 결합
data = np.array([x,y])
data

# concatenate는 차원이 기존 행렬과 같은 상태로 합쳐지고 array는 차원이 하나 커진다

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[33, 44, 55],
        [11, 22, 66]]])

두 결합 방법의 차이점을 이 마크다운에 설명해주세요

## 5. 마크다운에 있는 array를 복사하여 다음 문제를 풀어주세요

a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])

단, a array는 변경이 없어야 합니다.
1. 각 행별로 열을 기준으로 오름차순 정렬
- 각 열별로 행을 기준으로 오름차순 정렬

In [47]:
a = np.array([[4, 3, 5, 7], [1, 12, 11, 9], [2, 15, 1, 14]])
# a array 출력
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [50]:
#각 행별로 열을 기준으로 오름차순 정렬
b = np.sort(a, axis = 1)
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [49]:
#각 열별로 행을 기준으로 오름차순 정렬
c = np.sort(a, axis = 0)
c

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [51]:
# a array 출력
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])