# NumPy Basics

### Review를 위한 단계
- 방식 : 기존 실습 자료 및 검색을 하면서 이해하고 주석 달기
- 파일명 : **step05_Review이름.ipynb** 제출

In [3]:
import numpy as np

## The NumPy ndarray: A Multidimensional Array Object

In [2]:
data = np.random.randn(2, 3)
data

array([[ 0.20167732, -1.107788  ,  0.01053467],
       [-1.50199847,  0.53592633,  0.67105626]])

In [3]:
data * 10
data + data

array([[ 0.40335463, -2.215576  ,  0.02106933],
       [-3.00399693,  1.07185265,  1.34211253]])

In [4]:
data.shape
data.dtype

dtype('float64')

### Creating ndarrays

In [5]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [6]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.ndim
arr2.shape

(2, 4)

In [8]:
arr1.dtype
arr2.dtype

dtype('int32')

In [7]:
np.zeros(10)
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [11]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype
arr2.dtype

dtype('int32')

In [9]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [13]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)


array([ 3, -1, -2,  0, 12, 10])

In [16]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Arithmetic with NumPy Arrays

In [18]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
1 / arr
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [17]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [43]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [44]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [45]:
arr_slice[1] = 123
arr

array([  0,   1,   2,   3,   4,  12, 123,  12,   8,   9])

In [21]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [59]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [49]:
arr2d[0][2]
arr2d[0, 2]

3

In [56]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr3d[1, 0]

array([7, 8, 9])

In [28]:
x = arr3d[1]
x
x[0]

array([7, 8, 9])

#### Indexing with slices

In [60]:
arr
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [61]:
arr2d
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [32]:
arr2d[1, :2]

array([4, 5])

In [33]:
arr2d[:2, 2]

array([3, 6])

In [34]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [35]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [62]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.58487996  0.17032575 -2.4369513   0.64234874]
 [-1.91703484  0.24593325  0.4551596  -1.33400398]
 [ 0.76327136 -1.5547035   0.45975083 -0.15021554]
 [-0.71967473  1.83592128 -1.58012056 -0.44150934]
 [-1.40273996 -1.31852172 -0.18119362  0.39420355]
 [ 0.98831646 -0.84714305 -0.01275616  1.52542932]
 [-1.24236523  0.00541214 -0.32458959 -0.19600598]]


In [63]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [64]:
data[names == 'Bob']

array([[ 0.58487996,  0.17032575, -2.4369513 ,  0.64234874],
       [-0.71967473,  1.83592128, -1.58012056, -0.44150934]])

In [66]:
data[names == 'Bob', 2:]
data[names == 'Bob', 3]

array([ 0.64234874, -0.44150934])

In [67]:
mask = (names == 'Bob') | (names == 'Will')
mask
data[mask]

array([[ 0.58487996,  0.17032575, -2.4369513 ,  0.64234874],
       [ 0.76327136, -1.5547035 ,  0.45975083, -0.15021554],
       [-0.71967473,  1.83592128, -1.58012056, -0.44150934],
       [-1.40273996, -1.31852172, -0.18119362,  0.39420355]])

In [41]:
data[data < 0] = 0
data

array([[2.6058747 , 0.40197337, 0.        , 0.        ],
       [0.        , 0.        , 0.62112301, 0.        ],
       [0.84749265, 0.        , 0.        , 0.        ],
       [2.19827303, 0.        , 0.        , 0.        ],
       [0.        , 0.20820514, 0.18443861, 0.        ],
       [1.72139668, 0.        , 1.78839377, 0.30687491],
       [0.04374939, 0.58619046, 0.24574499, 2.43012532]])

In [42]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.62112301, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.72139668, 0.        , 1.78839377, 0.30687491],
       [0.04374939, 0.58619046, 0.24574499, 2.43012532]])

### Transposing Arrays and Swapping Axes

In [66]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [73]:
arr = np.arange(15).reshape((5, 3))
print(arr)
print('-------------')
print(arr.T)

print('-------------')
np.dot(arr.T, arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
-------------
[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]
-------------


array([[270, 300, 330],
       [300, 335, 370],
       [330, 370, 410]])

In [69]:
print(np.arange(16))

arr = np.arange(16).reshape((2, 2, 4))
print(arr)

print("--------------")

v = np.transpose(arr)
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
--------------
[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


In [88]:
print(arr)
arr.swapaxes(1, 2)
print("------------------")
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [87]:
arr.swapaxes(0, 2)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

## Universal Functions: Fast Element-Wise Array Functions

In [48]:
arr = np.arange(10)
arr
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [49]:
x = np.random.randn(8)
y = np.random.randn(8)
x
y
np.maximum(x, y)

array([-0.09331708,  0.76231744,  1.57213867, -0.87285515,  0.83639626,
        0.46625553,  0.97797565,  0.11063288])

In [75]:
arr = np.random.randn(7) * 5
print(arr)
print("----------------------")
remainder, whole_part = np.modf(arr)
print(remainder, whole_part)

[-0.87123538 -7.39682351 -3.13616766 -1.07465777 -3.2418139   3.46969009
 -7.79712084]
----------------------
[-0.87123538 -0.39682351 -0.13616766 -0.07465777 -0.2418139   0.46969009
 -0.79712084] [-0. -7. -3. -1. -3.  3. -7.]


In [76]:
print(arr)
np.sqrt(arr)
np.sqrt(arr, arr)
print(arr)

[-0.87123538 -7.39682351 -3.13616766 -1.07465777 -3.2418139   3.46969009
 -7.79712084]
[       nan        nan        nan        nan        nan 1.86271041
        nan]


C:\Users\Kimhyekyung\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  
C:\Users\Kimhyekyung\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


### Expressing Conditional Logic as Array Operations

In [52]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [53]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [54]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [55]:
arr = np.random.randn(4, 4)
arr
arr > 0
np.where(arr > 0, 2, -2)

array([[ 2,  2,  2,  2],
       [-2,  2, -2,  2],
       [-2,  2,  2,  2],
       [-2,  2, -2, -2]])

In [56]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[ 2.        ,  2.        ,  2.        ,  2.        ],
       [-2.03017964,  2.        , -1.38027551,  2.        ],
       [-0.63654054,  2.        ,  2.        ,  2.        ],
       [-1.04975622,  2.        , -0.87105063, -0.08547446]])

### Mathematical and Statistical Methods

In [57]:
arr = np.random.randn(5, 4)
arr
arr.mean()
np.mean(arr)
arr.sum()

3.7820476836028147

In [58]:
arr.mean(axis=1)
arr.sum(axis=0)

array([-1.30050514,  4.7178652 ,  0.12208804,  0.24259959])

In [59]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [60]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr
arr.cumsum(axis=0)
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

### Methods for Boolean Arrays

In [61]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

57

In [62]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

False

### Sorting

In [63]:
arr = np.random.randn(6)
print(arr)
arr.sort()
print(arr)

[-0.63727832 -0.90658992  0.9756279  -0.89038993  0.08202743  0.35269058]
[-0.90658992 -0.89038993 -0.63727832  0.08202743  0.35269058  0.9756279 ]


In [64]:
arr = np.random.randn(5, 3)
print(arr)
arr.sort(1)
print(arr)

[[ 0.14396298  0.39988242 -0.23906649]
 [-0.93194844 -2.04231778  0.37704838]
 [-0.13861966 -0.67890454  0.8203445 ]
 [ 0.99445146  0.13656934 -1.18450948]
 [ 0.13434072 -1.35606031  0.49779992]]
[[-0.23906649  0.14396298  0.39988242]
 [-2.04231778 -0.93194844  0.37704838]
 [-0.67890454 -0.13861966  0.8203445 ]
 [-1.18450948  0.13656934  0.99445146]
 [-1.35606031  0.13434072  0.49779992]]
